# [El Camino College] Notebook: CalEnviroScreen Exploration

**This notebook will put together everything you've learned so far and include new ways of interpreting data .**

### Learning Objectives

In this notebook, you will learn about:
- *insert learning objectives*

### Table of Contents
   
1. [Introduction](#0) <br>

-------------------------------------------------------------------

## 1. Introduction <a id='0'></a>

→ Explore the data, observe how many rows/columns and what they correspond to \
→ Subset different LA census tracts including El Camino's (create interactive graph they can play around with) \
→ Local rates of (asthma, pollution ) , LA wide rates, Cal  state wide (ex. compare local to higher level state averages)

In [1]:
import numpy as np
import pandas as pd

In [4]:
enviro = pd.read_csv('enviro.csv')
enviro

,Census Tract,Total Population,California County,ZIP,Approximate Location,Longitude,Latitude,CES 4.0 Score,CES 4.0 Percentile,CES 4.0 Percentile Range,...,Linguistic Isolation Pctl,Poverty,Poverty Pctl,Unemployment,Unemployment Pctl,Housing Burden,Housing Burden Pctl,Pop. Char.,Pop. Char. Score,Pop. Char. Pctl
0,6019001100,2780,Fresno,93706,Fresno,-119.781696,36.709695,93.18,100.00,95-100% (highest scores),...,79.37,76.0,98.92,12.8,93.83,30.3,91.04,93.16,9.66,99.72
1,6077000700,4680,San Joaquin,95206,Stockton,-121.287873,37.943173,86.65,99.99,95-100% (highest scores),...,95.53,73.2,98.39,19.8,99.21,31.2,92.28,93.17,9.66,99.74
2,6037204920,2751,Los Angeles,90023,Los Angeles,-118.197497,34.017500,82.39,99.97,95-100% (highest scores),...,81.55,62.6,93.39,6.4,61.53,20.3,63.97,83.75,8.69,95.79
3,6019000700,3664,Fresno,93706,Fresno,-119.827707,36.734535,81.33,99.96,95-100% (highest scores),...,78.71,65.7,95.35,15.7,97.35,35.4,96.41,94.64,9.82,99.89
4,6019000200,2689,Fresno,93706,Fresno,-119.805504,36.735491,80.75,99.95,95-100% (highest scores),...,86.56,72.7,98.30,13.7,95.29,32.7,94.16,95.40,9.90,99.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2305,6059052404,4220,Orange,92618,Irvine,-117.719107,33.673870,17.51,31.58,30-35%,...,64.81,11.9,14.48,5.3,48.26,NaN,NaN,20.65,2.14,8.57
2306,6037550000,1982,Los Angeles,90650,Norwalk,-118.067176,33.923946,NaN,NaN,NaN,...,NaN,74.2,98.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2307,6071980100,0,San Bernardino,92408,San Bernardino,-117.239834,34.097865,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2308,6073003800,6372,San Diego,92136,San Diego,-117.120798,32.683534,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2309,6037402803,3270,Los Angeles,91766,Pomona,-117.745305,34.047849,36.06,69.23,65-70%,...,87.81,53.8,85.88,6.8,65.63,22.6,72.60,71.12,7.38,81.58

Let's take a look at El Camino College's census tract data. Their tract # is **6037603702**.

In [8]:
ecc = enviro[enviro['Census Tract'] == 6037603702]
ecc

,Census Tract,Total Population,California County,ZIP,Approximate Location,Longitude,Latitude,CES 4.0 Score,CES 4.0 Percentile,CES 4.0 Percentile Range,...,Linguistic Isolation Pctl,Poverty,Poverty Pctl,Unemployment,Unemployment Pctl,Housing Burden,Housing Burden Pctl,Pop. Char.,Pop. Char. Score,Pop. Char. Pctl
2087,6037603702,4777,Los Angeles,90506,Alondra Park,-118.339382,33.882996,38.32,72.66,70-75%,...,40.9,21.9,38.13,6.0,57.25,8.4,8.04,57.25,5.94,61.3

## 2. Exploring by Region <a id='1'></a>

→ Split data into different neighborhoods of LA \
→ Focus subsetting health outcomes (PM2.5, lead, groundwater threats, pollution burden, asthma), particularly in lower-income neighborhoods